//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("dbModel", "FK_aviones_tipo", "tipo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcApplication1.Models.tipo), "aviones", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication1.Models.aviones), true)]
[assembly: EdmRelationshipAttribute("dbModel", "FK_piloto_avion_aviones", "aviones", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApplication1.Models.aviones), "piloto_avion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication1.Models.piloto_avion), true)]
[assembly: EdmRelationshipAttribute("dbModel", "FK_piloto_avion_pilotos", "pilotos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApplication1.Models.pilotos), "piloto_avion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication1.Models.piloto_avion), true)]

#endregion

namespace MvcApplication1.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class dbEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto dbEntities usando la cadena de conexión encontrada en la sección 'dbEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public dbEntities() : base("name=dbEntities", "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto dbEntities.
        /// </summary>
        public dbEntities(string connectionString) : base(connectionString, "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto dbEntities.
        /// </summary>
        public dbEntities(EntityConnection connection) : base(connection, "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<aviones> aviones
        {
            get
            {
                if ((_aviones == null))
                {
                    _aviones = base.CreateObjectSet<aviones>("aviones");
                }
                return _aviones;
            }
        }
        private ObjectSet<aviones> _aviones;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tipo> tipo
        {
            get
            {
                if ((_tipo == null))
                {
                    _tipo = base.CreateObjectSet<tipo>("tipo");
                }
                return _tipo;
            }
        }
        private ObjectSet<tipo> _tipo;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<piloto_avion> piloto_avion
        {
            get
            {
                if ((_piloto_avion == null))
                {
                    _piloto_avion = base.CreateObjectSet<piloto_avion>("piloto_avion");
                }
                return _piloto_avion;
            }
        }
        private ObjectSet<piloto_avion> _piloto_avion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<pilotos> pilotos
        {
            get
            {
                if ((_pilotos == null))
                {
                    _pilotos = base.CreateObjectSet<pilotos>("pilotos");
                }
                return _pilotos;
            }
        }
        private ObjectSet<pilotos> _pilotos;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet aviones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToaviones(aviones aviones)
        {
            base.AddObject("aviones", aviones);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tipo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotipo(tipo tipo)
        {
            base.AddObject("tipo", tipo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet piloto_avion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTopiloto_avion(piloto_avion piloto_avion)
        {
            base.AddObject("piloto_avion", piloto_avion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet pilotos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTopilotos(pilotos pilotos)
        {
            base.AddObject("pilotos", pilotos);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="aviones")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class aviones : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto aviones.
        /// </summary>
        /// <param name="id_aviones">Valor inicial de la propiedad id_aviones.</param>
        public static aviones Createaviones(global::System.Int32 id_aviones)
        {
            aviones aviones = new aviones();
            aviones.id_aviones = id_aviones;
            return aviones;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_aviones
        {
            get
            {
                return _id_aviones;
            }
            set
            {
                if (_id_aviones != value)
                {
                    Onid_avionesChanging(value);
                    ReportPropertyChanging("id_aviones");
                    _id_aviones = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_aviones");
                    Onid_avionesChanged();
                }
            }
        }
        private global::System.Int32 _id_aviones;
        partial void Onid_avionesChanging(global::System.Int32 value);
        partial void Onid_avionesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String marca
        {
            get
            {
                return _marca;
            }
            set
            {
                OnmarcaChanging(value);
                ReportPropertyChanging("marca");
                _marca = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("marca");
                OnmarcaChanged();
            }
        }
        private global::System.String _marca;
        partial void OnmarcaChanging(global::System.String value);
        partial void OnmarcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> asi1
        {
            get
            {
                return _asi1;
            }
            set
            {
                Onasi1Changing(value);
                ReportPropertyChanging("asi1");
                _asi1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("asi1");
                Onasi1Changed();
            }
        }
        private Nullable<global::System.Int32> _asi1;
        partial void Onasi1Changing(Nullable<global::System.Int32> value);
        partial void Onasi1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> asi2
        {
            get
            {
                return _asi2;
            }
            set
            {
                Onasi2Changing(value);
                ReportPropertyChanging("asi2");
                _asi2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("asi2");
                Onasi2Changed();
            }
        }
        private Nullable<global::System.Int32> _asi2;
        partial void Onasi2Changing(Nullable<global::System.Int32> value);
        partial void Onasi2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> asi3
        {
            get
            {
                return _asi3;
            }
            set
            {
                Onasi3Changing(value);
                ReportPropertyChanging("asi3");
                _asi3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("asi3");
                Onasi3Changed();
            }
        }
        private Nullable<global::System.Int32> _asi3;
        partial void Onasi3Changing(Nullable<global::System.Int32> value);
        partial void Onasi3Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> comb
        {
            get
            {
                return _comb;
            }
            set
            {
                OncombChanging(value);
                ReportPropertyChanging("comb");
                _comb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("comb");
                OncombChanged();
            }
        }
        private Nullable<global::System.Int32> _comb;
        partial void OncombChanging(Nullable<global::System.Int32> value);
        partial void OncombChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_tipo
        {
            get
            {
                return _id_tipo;
            }
            set
            {
                Onid_tipoChanging(value);
                ReportPropertyChanging("id_tipo");
                _id_tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_tipo");
                Onid_tipoChanged();
            }
        }
        private Nullable<global::System.Int32> _id_tipo;
        partial void Onid_tipoChanging(Nullable<global::System.Int32> value);
        partial void Onid_tipoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_aviones_tipo", "tipo")]
        public tipo tipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo>("dbModel.FK_aviones_tipo", "tipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo>("dbModel.FK_aviones_tipo", "tipo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tipo> tipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo>("dbModel.FK_aviones_tipo", "tipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tipo>("dbModel.FK_aviones_tipo", "tipo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_piloto_avion_aviones", "piloto_avion")]
        public EntityCollection<piloto_avion> piloto_avion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<piloto_avion>("dbModel.FK_piloto_avion_aviones", "piloto_avion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<piloto_avion>("dbModel.FK_piloto_avion_aviones", "piloto_avion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="piloto_avion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class piloto_avion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto piloto_avion.
        /// </summary>
        /// <param name="id_avion_piloto">Valor inicial de la propiedad id_avion_piloto.</param>
        /// <param name="id_piloto">Valor inicial de la propiedad id_piloto.</param>
        /// <param name="id_aviones">Valor inicial de la propiedad id_aviones.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static piloto_avion Createpiloto_avion(global::System.Int32 id_avion_piloto, global::System.Int32 id_piloto, global::System.Int32 id_aviones, global::System.Boolean estado)
        {
            piloto_avion piloto_avion = new piloto_avion();
            piloto_avion.id_avion_piloto = id_avion_piloto;
            piloto_avion.id_piloto = id_piloto;
            piloto_avion.id_aviones = id_aviones;
            piloto_avion.estado = estado;
            return piloto_avion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_avion_piloto
        {
            get
            {
                return _id_avion_piloto;
            }
            set
            {
                if (_id_avion_piloto != value)
                {
                    Onid_avion_pilotoChanging(value);
                    ReportPropertyChanging("id_avion_piloto");
                    _id_avion_piloto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_avion_piloto");
                    Onid_avion_pilotoChanged();
                }
            }
        }
        private global::System.Int32 _id_avion_piloto;
        partial void Onid_avion_pilotoChanging(global::System.Int32 value);
        partial void Onid_avion_pilotoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_piloto
        {
            get
            {
                return _id_piloto;
            }
            set
            {
                Onid_pilotoChanging(value);
                ReportPropertyChanging("id_piloto");
                _id_piloto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_piloto");
                Onid_pilotoChanged();
            }
        }
        private global::System.Int32 _id_piloto;
        partial void Onid_pilotoChanging(global::System.Int32 value);
        partial void Onid_pilotoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_aviones
        {
            get
            {
                return _id_aviones;
            }
            set
            {
                Onid_avionesChanging(value);
                ReportPropertyChanging("id_aviones");
                _id_aviones = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_aviones");
                Onid_avionesChanged();
            }
        }
        private global::System.Int32 _id_aviones;
        partial void Onid_avionesChanging(global::System.Int32 value);
        partial void Onid_avionesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_piloto_avion_aviones", "aviones")]
        public aviones aviones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aviones>("dbModel.FK_piloto_avion_aviones", "aviones").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aviones>("dbModel.FK_piloto_avion_aviones", "aviones").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<aviones> avionesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<aviones>("dbModel.FK_piloto_avion_aviones", "aviones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<aviones>("dbModel.FK_piloto_avion_aviones", "aviones", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_piloto_avion_pilotos", "pilotos")]
        public pilotos pilotos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<pilotos>("dbModel.FK_piloto_avion_pilotos", "pilotos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<pilotos>("dbModel.FK_piloto_avion_pilotos", "pilotos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<pilotos> pilotosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<pilotos>("dbModel.FK_piloto_avion_pilotos", "pilotos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<pilotos>("dbModel.FK_piloto_avion_pilotos", "pilotos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="pilotos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pilotos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto pilotos.
        /// </summary>
        /// <param name="id_piloto">Valor inicial de la propiedad id_piloto.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="apellidos">Valor inicial de la propiedad apellidos.</param>
        /// <param name="edad">Valor inicial de la propiedad edad.</param>
        /// <param name="grado">Valor inicial de la propiedad grado.</param>
        public static pilotos Createpilotos(global::System.Int32 id_piloto, global::System.String nombre, global::System.String apellidos, global::System.Int32 edad, global::System.String grado)
        {
            pilotos pilotos = new pilotos();
            pilotos.id_piloto = id_piloto;
            pilotos.nombre = nombre;
            pilotos.apellidos = apellidos;
            pilotos.edad = edad;
            pilotos.grado = grado;
            return pilotos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_piloto
        {
            get
            {
                return _id_piloto;
            }
            set
            {
                if (_id_piloto != value)
                {
                    Onid_pilotoChanging(value);
                    ReportPropertyChanging("id_piloto");
                    _id_piloto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_piloto");
                    Onid_pilotoChanged();
                }
            }
        }
        private global::System.Int32 _id_piloto;
        partial void Onid_pilotoChanging(global::System.Int32 value);
        partial void Onid_pilotoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellidos
        {
            get
            {
                return _apellidos;
            }
            set
            {
                OnapellidosChanging(value);
                ReportPropertyChanging("apellidos");
                _apellidos = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellidos");
                OnapellidosChanged();
            }
        }
        private global::System.String _apellidos;
        partial void OnapellidosChanging(global::System.String value);
        partial void OnapellidosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 edad
        {
            get
            {
                return _edad;
            }
            set
            {
                OnedadChanging(value);
                ReportPropertyChanging("edad");
                _edad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("edad");
                OnedadChanged();
            }
        }
        private global::System.Int32 _edad;
        partial void OnedadChanging(global::System.Int32 value);
        partial void OnedadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String grado
        {
            get
            {
                return _grado;
            }
            set
            {
                OngradoChanging(value);
                ReportPropertyChanging("grado");
                _grado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("grado");
                OngradoChanged();
            }
        }
        private global::System.String _grado;
        partial void OngradoChanging(global::System.String value);
        partial void OngradoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_piloto_avion_pilotos", "piloto_avion")]
        public EntityCollection<piloto_avion> piloto_avion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<piloto_avion>("dbModel.FK_piloto_avion_pilotos", "piloto_avion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<piloto_avion>("dbModel.FK_piloto_avion_pilotos", "piloto_avion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="tipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tipo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tipo.
        /// </summary>
        /// <param name="id_tipo">Valor inicial de la propiedad id_tipo.</param>
        public static tipo Createtipo(global::System.Int32 id_tipo)
        {
            tipo tipo = new tipo();
            tipo.id_tipo = id_tipo;
            return tipo;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tipo
        {
            get
            {
                return _id_tipo;
            }
            set
            {
                if (_id_tipo != value)
                {
                    Onid_tipoChanging(value);
                    ReportPropertyChanging("id_tipo");
                    _id_tipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tipo");
                    Onid_tipoChanged();
                }
            }
        }
        private global::System.Int32 _id_tipo;
        partial void Onid_tipoChanging(global::System.Int32 value);
        partial void Onid_tipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbModel", "FK_aviones_tipo", "aviones")]
        public EntityCollection<aviones> aviones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<aviones>("dbModel.FK_aviones_tipo", "aviones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<aviones>("dbModel.FK_aviones_tipo", "aviones", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
